/**
 * Enemy Configuration
 * 
 * Contains all enemy type definitions including base stats,
 * visual properties, and behavior configurations.
 */

export const enemiesConfig = [
    {
        key: 'enemy_basic',
        enemy_body_image: 'src/assets/images/enemy_basic.png',
        enemy_legs_image: 'src/assets/images/enemy_basic_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 500,
        shootInterval: 1000,
        shootRange: 350,
        projectileDamage: 10,
        xpValue: 1,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common'
    },
    {
        key: 'enemy_bandido',
        enemy_body_image: 'src/assets/images/enemy_bandido.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido_legs.png',
        speed: 200,
        size: 32,
        damage: 10,
        health: 80,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.2,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        hitSoundKey: 'hit',
        dropChance: 0.08,
        lootTable: 'common'
    },
    {
        key: 'enemy_bandido2',
        enemy_body_image: 'src/assets/images/enemy_bandido2.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido2_legs.png',
        speed: 200,
        size: 32,
        damage: 15,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 40,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.25,
        legsScale: 0.25,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1.4 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_bolsonarista',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista_legs.png',
        speed: 250,
        size: 32,
        damage: 20,
        health: 40,
        spawnDistance: 700,
        maxOnScreen: 30,
        xpDropChance: 0.85,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 3,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        hitSoundKey: 'hit',
        dropChance: 0.15,
        lootTable: 'ucommon'
    },
    {
        key: 'enemy_bolsonarista2',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista2.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_centrao',
        enemy_body_image: 'src/assets/images/enemy_centrao.png',
        enemy_legs_image: 'src/assets/images/enemy_centrao_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_comunista',
        enemy_body_image: 'src/assets/images/enemy_comunista.png',
        enemy_legs_image: 'src/assets/images/enemy_comunista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_favela',
        enemy_body_image: 'src/assets/images/enemy_favela.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista',
        enemy_body_image: 'src/assets/images/enemy_feminista.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista_doida',
        enemy_body_image: 'src/assets/images/enemy_feminista_doida.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher',
        enemy_body_image: 'src/assets/images/enemy_history_teacher.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher2',
        enemy_body_image: 'src/assets/images/enemy_history_teacher2.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_mendigo',
        enemy_body_image: 'src/assets/images/enemy_mendigo.png',
        enemy_legs_image: 'src/assets/images/enemy_mendigo_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo2',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo2.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_petista',
        enemy_body_image: 'src/assets/images/enemy_petista.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_politico',
        enemy_body_image: 'src/assets/images/enemy_politico.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 1500,
        shootRange: 400,
        projectileDamage: 15,
        xpValue: 2,
        bodyScale: 0.3,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: -6, y: 16 },
        legOrigin: { x: 0.5, y: -1 },
        animation: {
            walkSwingSpeed: 0.015,
            walkSwingAmplitude: 0.15,
            walkBobSpeed: 0.02,
            walkBobAmplitude: 1
        },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    }
];

/**
 * Boss Configuration
 */
export const bossesConfig = [
    {
        key: 'boss_orc_king',
        name: 'Rei Orc',
        baseEnemy: 'enemy_basic',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 2.0,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFF4444,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    }
];
